-- =====================================================
-- SALES PERFORMANCE DASHBOARD
-- 04_analysis_queries.sql
-- Description: Business analysis queries
-- =====================================================

-- =====================================================
-- KPI 01 - Total Revenue
-- Description:
-- Calculates the total revenue generated from all customer payments.
-- =====================================================

SELECT
    ROUND(SUM(payment_value)::NUMERIC, 2) AS total_revenue
FROM public.olist_order_payments_dataset;

-- =====================================================
-- KPI 02 - Total Orders
-- Description:
-- Counts the total number of orders placed by customers.
-- =====================================================

SELECT
    COUNT(*) AS total_orders
FROM public.olist_orders_dataset;

-- =====================================================
-- KPI 03 - Customer Records
-- Description:
-- Counts the total number of customer records.
-- =====================================================

SELECT
    COUNT(*) AS total_customer_records
FROM public.olist_customers_dataset;

-- =====================================================
-- KPI 04 - Average Order Value
-- Description:
-- Calculates the average value paid per order.
-- =====================================================

SELECT
    ROUND(AVG(payment_value)::NUMERIC, 2) AS average_order_value
FROM public.olist_order_payments_dataset;

-- =====================================================
-- KPI 05 - Average Review Score
-- Description:
-- Calculates the average customer review score.
-- =====================================================

SELECT
    ROUND(AVG(review_score)::NUMERIC, 2) AS average_review_score
FROM public.olist_order_reviews_dataset;

-- =====================================================
-- KPI 06 - Total Unique Customers
-- Description:
-- Calculates the total number of unique customers.
-- =====================================================

SELECT
    COUNT(DISTINCT customer_unique_id) AS total_unique_customers
FROM public.olist_customers_dataset;

-- =====================================================
-- ANALYSIS 01 - Orders by Status
-- Description:
-- Counts the number of orders for each order status.
-- =====================================================

SELECT
    order_status,
    COUNT(*) AS total_orders
FROM public.olist_orders_dataset
GROUP BY order_status
ORDER BY total_orders DESC;

-- =====================================================
-- ANALYSIS 02 - Revenue by Month
-- Description:
-- Calculates total revenue grouped by year and month.
-- =====================================================

SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    ROUND(SUM(op.payment_value)::NUMERIC, 2) AS total_revenue
FROM public.olist_orders_dataset o
JOIN public.olist_order_payments_dataset op
    ON o.order_id = op.order_id
GROUP BY DATE_TRUNC('month', o.order_purchase_timestamp)
ORDER BY month;

-- =====================================================
-- ANALYSIS 03 - Top 10 Product Categories by Revenue
-- Description:
-- Calculates the total revenue generated by each product category.
-- Displays product category names in English.
-- =====================================================

SELECT
    t.product_category_name_english AS product_category,
    ROUND(SUM(op.payment_value)::NUMERIC, 2) AS total_revenue
FROM public.olist_products_dataset p
JOIN public.product_category_name_translation t
    ON p.product_category_name = t.product_category_name
JOIN public.olist_order_items_dataset oi
    ON p.product_id = oi.product_id
JOIN public.olist_order_payments_dataset op
    ON oi.order_id = op.order_id
GROUP BY t.product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;

-- =====================================================
-- ANALYSIS 04 - Revenue by State
-- Description:
-- Calculates total revenue generated by each Brazilian state.
-- =====================================================

SELECT
    c.customer_state,
    ROUND(SUM(op.payment_value)::NUMERIC, 2) AS total_revenue
FROM public.olist_orders_dataset o
JOIN public.olist_customers_dataset c
    ON o.customer_id = c.customer_id
JOIN public.olist_order_payments_dataset op
    ON o.order_id = op.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;

-- =====================================================
-- ANALYSIS 05 - Top 10 Sellers by Revenue
-- Description:
-- Calculates the total revenue generated by each seller.
-- =====================================================

SELECT
    oi.seller_id,
    ROUND(SUM(op.payment_value)::NUMERIC, 2) AS total_revenue
FROM public.olist_order_items_dataset oi
JOIN public.olist_order_payments_dataset op
    ON oi.order_id = op.order_id
GROUP BY oi.seller_id
ORDER BY total_revenue DESC
LIMIT 10;

-- =====================================================
-- ANALYSIS 06 - Average Delivery Time by State
-- Description:
-- Calculates the average delivery time (in days) for each state.
-- =====================================================

SELECT
    c.customer_state,
    ROUND(
        AVG(
            EXTRACT(EPOCH FROM (
                o.order_delivered_customer_date - o.order_purchase_timestamp
            )) / 86400
        )::NUMERIC,
        2
    ) AS average_delivery_days
FROM public.olist_orders_dataset o
JOIN public.olist_customers_dataset c
    ON o.customer_id = c.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY average_delivery_days;